version: '3.5'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    container_name: postgres_container
    image: postgres:11
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      #PGDATA: /data/postgres
      POSTGRES_INITDB_ARGS: "-E UTF8 -T template0 --lc-collate=ru_RU.UTF-8 --lc-ctype=ru_RU.UTF-8"
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
    volumes:
      #- pg-data:/data/postgres
      #- pg-data:/var/lib/postgresql/data
      - ./pg-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-veprikov}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-pass}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5555}:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    #pg-data:
    pgadmin:
