FROM postgres:11

RUN apt-get update
RUN echo "ru_RU.UTF-8 UTF-8" >> /etc/locale.gen
RUN locale-gen
RUN update-locale LANG=ru_RU.UTF-8
RUN localedef -i ru_RU  -c -f UTF-8 -A /usr/share/locale/locale.alias ru_RU.UTF-8

ENV LANG ru_RU.UTF-8

# exec DDL & DML
ADD src/resources/db/migration/*.sql /docker-entrypoint-initdb.d/

EXPOSE 5432
CMD ["postgres"]
